### ISSUE TITLE
Building capture breaks when too much zoom happens

### ISSUE THREAD

**Issue by alexander-sheehan** [dartmouth-cs98/18w-paintthetown#105]
When the player zooms out too much, buildings cannot be captured, when they zoom back in, the capture function starts working again, but wrld3d doesn't recognize any building clicked on.

**Comment by alexander-sheehan** [comment]
This appears to happen at the moment when the roads despawn due to distance zoomed out

**Comment by alexander-sheehan** [comment]
Right now, the most valid approach to fixes this seems to be limiting how much the user can zoom out- will be fixed soon

**Comment by Shoopalapa** [comment]
Able to limit zooming out, still needs some refining but it should handle this for now
